version: "3.8"

services:
  example-app:
    image: example:1.0.0
    container_name: example-app
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@exampledb:5432/example
    depends_on:
      - exampledb
    networks:
      - example-bridge

  exampledb:
    image: postgres:16.4
    container_name: exampledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - example-bridge

networks:
  example-bridge:
    driver: bridge

volumes:
  db-data:
    driver: local
