apiVersion: v1
kind: Service
metadata:
  name: date-service
spec:
  type: NodePort
  selector:
    app: date-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32000
