apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: date-app
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: date-app
    spec:
      containers:
        - name: date-app
          image: date-app:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
